# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NexOrderUserService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: practiceregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A489B4C0D1324353B68599E45C3E8466 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_0DFEA3E064A1492AA613FCAF899CB529 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: practiceregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A489B4C0D1324353B68599E45C3E8466 }}/nexorderuserservice:${{ github.sha }}
          file: NexOrder.UserService/Dockerfile
          build-args: |
            GITHUB_USERNAME=${{ github.repository_owner }}
            GITHUB_TOKEN=${{ secrets.NUGET_TOKEN }}

  migrate:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-ef (global)
      run: |
        dotnet tool install --global dotnet-ef --version 8.0.*
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Add GitHub NuGet source
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
          --name github \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.NUGET_TOKEN }} \
          --store-password-in-clear-text

    - name: Run EF Core migrations
      env:
        DB_CONNECTION: ${{ secrets.SQL_CONN }}
      run: |
        dotnet ef database update \
          --project NexOrder.UserService.Infrastructure \
          --startup-project NexOrder.UserService.Infrastructure \
          --connection "$DB_CONNECTION"

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1EE83DE66DDC428999113C345C5E7790 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30E437FB3F4E4222A5EB0D3AEDD324A4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4E1B912C25F4980968D997A9890B8D0 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NexOrderUserService'
          slot-name: 'Production'
          images: 'practiceregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A489B4C0D1324353B68599E45C3E8466 }}/nexorderuserservice:${{ github.sha }}'

          
